from z3 import *
def embeed(constraints):
    A = BitVec('A', 5)
    B = BitVec('B', 5)
    C = BitVec('C', 5)
    D = BitVec('D', 5)
    E = BitVec('E', 5)
    F = BitVec('F', 5)
    G = BitVec('G', 5)
    H = BitVec('H', 5)
    I = BitVec('I', 5)
    J = BitVec('J', 5)
    K = BitVec('K', 5)
    L = BitVec('L', 5)
    constraints.add(ULT(A, 16))
    constraints.add(ULT(B, 16))
    constraints.add(ULT(C, 16))
    constraints.add(ULT(D, 16))
    constraints.add(ULT(E, 16))
    constraints.add(ULT(F, 16))
    constraints.add(ULT(G, 16))
    constraints.add(ULT(H, 16))
    constraints.add(ULT(I, 16))
    constraints.add(ULT(J, 16))
    constraints.add(ULT(K, 16))
    constraints.add(ULT(L, 16))
    constraints.add((A + B) == C)
    constraints.add((D + E) == F)
    constraints.add((G + H) == I)
    constraints.add((J + K) == L)